import React from 'react'
import '@/styles/tailwind.css'
import '@/styles/globals.css'
import getQueryClient from './getQueryClient'
import { Hydrate, QueryClientProvider, dehydrate } from '@tanstack/react-query'
import { prefetchEncPublicKey } from '@/data/hooks/auth'
import Providers from './Provider'

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    {children}
                    <div id="portal" />
                </Providers>
            </body>
        </html>
    )
}
